spring.application.name=shop
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/hexashop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# this secret must be saved in a vault and read it from there
jwtSecret=and0LXNlY3JldC1mb3ItaGV4YS1zaG9waW5nLWNhcnQtd2l0aC1hcGktZmlyc3Q=
jwtSecret.valid.timeframe=7200

#logging.level.org.springframework.security=DEBUG
